{
 "title": "Air quality",
 "time": { "from": "2025-10-19T20:00:00.000Z", "to": "2025-10-23T23:00:00.000Z" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Major air polutants in Mombasa",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "default_keyspace",
     "rawSql": "SELECT \n  AVG(carbon_monoxide) AS carbon_monoxide, \n  city, \n  AVG(nitrogen_dioxide) AS nitrogen_dioxide, \n  AVG(sulphur_dioxide) AS sulphur_dioxide, \n  AVG(pm2_5) AS pm2_5, \n  AVG(pm10) AS pm10\nFROM default_keyspace.air_quality_data \nWHERE city = 'mombasa' \nGROUP BY timestamp;"
    }
   ]
  },
  {
   "title": "Polutants in nairobi",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "default_keyspace",
     "rawSql": "SELECT \n  AVG(carbon_monoxide) AS carbon_monoxide, \n  city, \n  AVG(nitrogen_dioxide) AS nitrogen_dioxide, \n  AVG(sulphur_dioxide) AS sulphur_dioxide, \n  AVG(pm2_5) AS pm2_5, \n  AVG(pm10) AS pm10\nFROM default_keyspace.air_quality_data \nWHERE city = 'nairobi' \nGROUP BY timestamp;"
    }
   ]
  },
  {
   "title": "Comparison between Mombasa and Nairobi",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "targets": [
    {
     "dataset": "default_keyspace",
     "rawSql": "SELECT \n  AVG(carbon_monoxide) AS carbon_monoxide, \n  city \nFROM default_keyspace.air_quality_data \nGROUP BY city; "
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Strongly correlated pollutants",
   "type": "timeseries",
   "description": "Its interesting to see that during the day time these pollutants are lower than at night, this is because even though theres less production at night, reduced atmosheric mixing",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "default_keyspace",
     "rawSql": "SELECT AVG(carbon_monoxide), AVG(nitrogen_dioxide), AVG(sulphur_dioxide), timestamp FROM default_keyspace.air_quality_data GROUP BY city, timestamp;"
    }
   ]
  },
  {
   "title": "The source of ground level ozone",
   "type": "timeseries",
   "description": "A higher uv index during the day leads to higher grond level ozone created from the reaction with nitogen diovide, leading to its deplition",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "dataset": "default_keyspace",
     "rawSql": "SELECT \n    timestamp AS time,\n    nitrogen_dioxide,\n    ozone/10 AS ozone,\n    uv_index\n\nFROM default_keyspace.air_quality_data;"
    }
   ]
  },
  {
   "title": "Dusty commutes",
   "type": "timeseries",
   "description": "During the morning times these is a significant spice in particles kicked up but commuters in the city and this slowly goes down over the course of the day ",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 26 },
   "targets": [
    {
     "dataset": "default_keyspace",
     "rawSql": "SELECT \n    timestamp,\n    AVG(pm2_5) AS avg_pm2_5,\n    AVG(pm10) AS avg_pm10,\n    city\nFROM default_keyspace.air_quality_data\nGROUP BY city, timestamp;\n"
    },
    {
     "dataset": "default_keyspace",
     "rawSql": "SELECT sulphur_dioxide FROM default_keyspace.air_quality_data LIMIT 50 "
    }
   ]
  }
 ]
}